service: project-app
provider:
  name: aws
  runtime: nodejs18.x
  stage: default
  region: ap-south-1
  memorySize: 128
functions:
  app:
    handler: app/app.handler
    events: 
      - http: 
          path: /
          method: ANY
      - http: 
          path: /{proxy+}
          method: ANY